import { StudioProjectState, PresetTemplate } from './types';

export const ASPECT_RATIOS = {
  '3:4': { width: 1080, height: 1440, label: '3:4 (Portrait Feed / Studio Default)', ratio: 3 / 4 },
  '9:16': { width: 1080, height: 1920, label: '9:16 (TikTok / Reels / Shorts)', ratio: 9 / 16 },
  '16:9': { width: 1920, height: 1080, label: '16:9 (Landscape / YouTube)', ratio: 16 / 9 },
  '1:1': { width: 1080, height: 1080, label: '1:1 (Square / Instagram)', ratio: 1 / 1 },
};

export const INITIAL_STUDIO_STATE: StudioProjectState = {
  aspectRatio: '3:4',
  canvasWidth: 1080,
  canvasHeight: 1440,
  duration: 15,
  currentTime: 0,
  isPlaying: false,
  masterVolume: 1,
  syncMode: 'sync-content',
  customDurationSeconds: 15,
  background: {
    videoUrl: '/recording.mp4',
    fileName: 'Recording 2026-08-24 094643.mp4',
    sourceType: 'recording',
    presetId: 'aurora-motion',
    blur: 6,
    opacity: 0.95,
    brightness: 0.9,
    contrast: 1.1,
    saturation: 1.2,
    scale: 1.1,
    fit: 'cover',
    volume: 0.3,
    isMuted: false,
    loop: true,
    playbackSpeed: 1.0,
    overlayGradient: 'dark-vignette',
    solidColorFallback: '#0f172a',
  },
  tabMockup: {
    videoUrl: '/recording.mp4',
    fileName: 'Recording 2026-08-24 094643.mp4',
    sourceType: 'recording',
    presetId: 'demo-app',
    style: 'safari-dark',
    tabTitle: 'studio.app — Video Canvas',
    tabUrl: 'https://studio.app/workspace/video-tab',
    showTabFavicon: true,
    showUrlBar: true,
    showWindowControls: true,
    borderRadius: 20,
    tabScale: 0.88,
    offsetX: 0,
    offsetY: 0,
    tilt3D: {
      enabled: false,
      rotateX: 4,
      rotateY: -4,
      perspective: 1200,
    },
    shadow: 'deep',
    border: 'glass',
    videoFit: 'cover',
    videoPadding: 0,
    volume: 1.0,
    isMuted: false,
    playbackSpeed: 1.0,
  },
  overlays: {
    headline: {
      enabled: false,
      text: '🚀 Next-Gen Video Showcase',
      subtext: 'Built with 3:4 dual-layer mockup studio',
      position: 'top',
      badgeColor: '#6366f1',
      textColor: '#ffffff',
      fontSize: 'md',
    },
    watermark: {
      enabled: false,
      text: 'STUDIO.AI',
      position: 'bottom-right',
      opacity: 0.6,
    },
    progressBar: {
      enabled: true,
      color: '#6366f1',
      height: 4,
    },
  },
};

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: 'saas-pro',
    name: 'SaaS Pro Dark',
    description: 'Clean dark background with frosted Safari tab and subtle glow.',
    category: 'Product Showcase',
    badge: 'Popular',
    previewGradient: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%)',
    config: {
      background: {
        ...INITIAL_STUDIO_STATE.background,
        blur: 8,
        opacity: 0.9,
        brightness: 0.85,
        contrast: 1.15,
        overlayGradient: 'radial-glow',
      },
      tabMockup: {
        ...INITIAL_STUDIO_STATE.tabMockup,
        style: 'safari-dark',
        shadow: 'glow-purple',
        border: 'glass',
        borderRadius: 22,
        tabScale: 0.86,
      },
    },
  },
  {
    id: 'cyber-neon',
    name: 'Cyberpunk Neon',
    description: 'High-contrast neon glow background with futuristic Arc glass tab.',
    category: 'Tech & Gaming',
    badge: 'Trending',
    previewGradient: 'linear-gradient(135deg, #09090b 0%, #083344 50%, #164e63 100%)',
    config: {
      background: {
        ...INITIAL_STUDIO_STATE.background,
        blur: 4,
        opacity: 1.0,
        brightness: 1.0,
        contrast: 1.3,
        saturation: 1.4,
        overlayGradient: 'cyber-mesh',
      },
      tabMockup: {
        ...INITIAL_STUDIO_STATE.tabMockup,
        style: 'arc-glass',
        shadow: 'glow-cyan',
        border: 'neon-gradient',
        borderRadius: 24,
        tabScale: 0.88,
      },
    },
  },
  {
    id: 'minimal-clean',
    name: 'Minimalist Clean',
    description: 'Soft blurred background with elegant frameless glass mockup.',
    category: 'Design & Portfolio',
    badge: 'Clean',
    previewGradient: 'linear-gradient(135deg, #18181b 0%, #27272a 50%, #18181b 100%)',
    config: {
      background: {
        ...INITIAL_STUDIO_STATE.background,
        blur: 16,
        opacity: 0.85,
        brightness: 0.9,
        contrast: 1.0,
        overlayGradient: 'dark-vignette',
      },
      tabMockup: {
        ...INITIAL_STUDIO_STATE.tabMockup,
        style: 'minimal-glass',
        shadow: 'soft',
        border: 'subtle',
        borderRadius: 16,
        tabScale: 0.9,
      },
    },
  },
  {
    id: 'tiktok-viral',
    name: 'Viral TikTok / Reel',
    description: 'High energy 3D tilt perspective with prominent top headline banner.',
    category: 'Social Media',
    badge: 'Viral',
    previewGradient: 'linear-gradient(135deg, #311042 0%, #4c1d95 50%, #1e1b4b 100%)',
    config: {
      background: {
        ...INITIAL_STUDIO_STATE.background,
        blur: 5,
        opacity: 0.95,
        brightness: 0.95,
        saturation: 1.3,
        overlayGradient: 'top-bottom-fade',
      },
      tabMockup: {
        ...INITIAL_STUDIO_STATE.tabMockup,
        style: 'safari-dark',
        shadow: 'deep',
        border: 'glass',
        borderRadius: 20,
        tabScale: 0.86,
        tilt3D: {
          enabled: true,
          rotateX: 6,
          rotateY: -5,
          perspective: 1100,
        },
      },
      overlays: {
        ...INITIAL_STUDIO_STATE.overlays,
        headline: {
          enabled: true,
          text: '🔥 MUST-SEE WORKFLOW',
          subtext: 'Double tap if this helps!',
          position: 'top',
          badgeColor: '#ec4899',
          textColor: '#ffffff',
          fontSize: 'md',
        },
      },
    },
  },
  {
    id: 'retro-classic',
    name: 'Retro Mac System',
    description: 'Nostalgic classic window styling with authentic vintage headers.',
    category: 'Retro & Aesthetic',
    badge: 'Retro',
    previewGradient: 'linear-gradient(135deg, #1c1917 0%, #292524 50%, #0c0a09 100%)',
    config: {
      background: {
        ...INITIAL_STUDIO_STATE.background,
        blur: 10,
        opacity: 0.9,
        brightness: 0.8,
        contrast: 1.2,
      },
      tabMockup: {
        ...INITIAL_STUDIO_STATE.tabMockup,
        style: 'retro-mac',
        shadow: 'deep',
        border: 'solid-dark',
        borderRadius: 12,
        tabScale: 0.85,
      },
    },
  },
];

export const BACKGROUND_PRESET_ANIMATIONS = [
  { id: 'aurora-motion', name: 'Aurora Liquid Waves', category: 'Gradient' },
  { id: 'cyber-grid', name: 'Cyberpunk Neon Grid', category: '3D Mesh' },
  { id: 'starfield-particles', name: 'Floating Nebula Stars', category: 'Cosmic' },
  { id: 'tech-code-stream', name: 'Matrix Code Flow', category: 'Developer' },
  { id: 'bokeh-ambient', name: 'Warm Bokeh Lights', category: 'Minimal' },
];
